name: ☁️ AWS Terraform S3 Backends
on:
  workflow_dispatch:
    inputs:
      applyTerraform:
        description: "Run Terraform Apply"
        required: true
        default: false
        type: boolean
  push:
    branches:
      - 'main'
    paths:
      - "terraform/**"
  pull_request:
    types: [opened, synchronize, reopened]
env:
  entrypoint: 0_iac_backends

jobs:
  terraform-plan-all:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    if: github.event.inputs.applyTerraform != 'true'
    strategy:
      matrix:
        env: [ backends ]
        region: [eu-west-2]
      fail-fast: false
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2
      - name: Plan AWS terraform
        uses: ./.github/workflows/composite/deploy-terraform
        with:
          region: ${{ matrix.region}}
          environment: ${{ matrix.env}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          runApply: false
          workingDirectory: ./terraform/${{ env.entrypoint}}

  terraform-apply-all:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    if: github.event.inputs.applyTerraform == 'true'
    strategy:
      matrix:
        env: [ backends ]
        region: [ eu-west-2 ]
      fail-fast: false
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2
      - name: Plan AWS terraform
        uses: ./.github/workflows/composite/deploy-terraform
        with:
          region: ${{ matrix.region}}
          environment: ${{ matrix.env}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          runApply: true
          workingDirectory: ./terraform/${{ env.entrypoint}}